### ISSUE TITLE
Setting the command variable prompt to utf-8 is not supported and entering utf-8 strings is not supported.

### ISSUE THREAD

**Issue by pdeantihuman** [skywind3000/asynctasks.vim#26]
There are actually two problems. 

## Setting the command variable prompt to utf-8 is not supported
The following is my command profile

### How to reproduce

```conf
 [test]
 command=echo $(?输入你的名字)
 cwd=<root>
```

### Phenomenon

It will complain
```
Traceback (most recent call last):
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 1242, in <module>
    exit(main())
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 1170, in main
    tm.interactive(mode)
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 1080, in interactive
    return self.task_run(text)
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 918, in task_run
    command = self.command_input(command)
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 852, in command_input
    text = raw_input(prompt)  # noqa: F821
UnicodeEncodeError: 'ascii' codec can't encode characters in position 16-21: ordinal not in range(128)
```

### How to reproduce

my command profile
```conf
 [test]
 command=echo $(?enter your name)
 cwd=<root>
```

and input

```
> $ task                                                             ⬡ 12.16.1 
Input argument (enter your name): 你好，世界
```

### Phenomenon

it would complain
```
Traceback (most recent call last):
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 1242, in <module>
    exit(main())
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 1170, in main
    tm.interactive(mode)
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 1080, in interactive
    return self.task_run(text)
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 918, in task_run
    command = self.command_input(command)
  File "/Users/johnd/program/asynctasks.vim/bin/asynctask.py", line 860, in command_input
    command = command.replace(mark, text)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

**Comment by skywind3000** [comment]
再试试，我改成默认用 python3 了。

**Comment by pdeantihuman** [comment]
This problem no longer exists.
